select * from customer limit 20

--Q1.What is the total revenue generated by male vs. female customer ?
Select "Gender", SUM("Purchase Amount (USD)") AS revenue
from customer
group by "Gender";

--Q2.Whice customers used a discount but still spent more than the average purchase amount ?
SELECT
    "Customer ID",
    "Purchase Amount (USD)"
FROM
    customer
WHERE
    "Discount Applied" = 'Yes'
    AND "Purchase Amount (USD)" >= (
        SELECT AVG("Purchase Amount (USD)")
        FROM customer
    );
	
--Q3.Compare the average Purchase Amounts between standard and express shipping.
select "Shipping Type" ,
ROUND(AVG("Purchase Amount (USD)"),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"

--Q4.Which 5 products have the highest percentage of purchase with discount applied ?
select "Item Purchased",
ROUND(SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as Discount_Rate
from customer
group by "Item Purchased"
order by Discount_Rate desc
limit 5;

--Q5.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select "Subscription Status",
count("Customer ID") as "Repeat_Buyers"
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

--Q6.What is the revenue contribution of each Age?
select "Age" ,
SUM("Purchase Amount (USD)") as Total_Revenue
from customer
group by "Age"
order by Total_Revenue desc;

--Q7. Find the Total sales by category
Select * from customer limit 20;
SELECT "Category", SUM("Purchase Amount (USD)") AS Total_Sales
FROM customer
GROUP BY "Category"
ORDER BY Total_Sales DESC;

--Q8..Impact of Discounts on Purchase Amount
Select * from customer limit 20;
SELECT "Discount Applied", AVG("Purchase Amount (USD)") AS Avg_Spent
FROM customer
GROUP BY "Discount Applied";

--Q9.Find Frequent shoppers (based on frequency column)
SELECT "Customer ID", "Frequency of Purchases"
FROM customer
ORDER BY "Frequency of Purchases" DESC
LIMIT 10;

--Q10.Find the Revenue by Total payment method
SELECT "Payment Method", SUM("Purchase Amount (USD)") AS Total_Revenue
FROM customer
GROUP BY "Payment Method";